### ISSUE TITLE
Bug Investigation: drawing offset

### ISSUE THREAD

**Issue by dbarenholz** [tobias0409/obsidian-cannote#4]
I've figured out the issue - documenting here because no more time now, and I don't want to forget. In the screenshot below I am logging the `canvas` from `NotesView` -- see snippet below.

```ts
const canvas = container.createEl("canvas", {
  cls: "note-canvas", 
  attr: {
    id: "note-canvas",
  }
});
console.log(canvas)
console.log(canvas.getBoundingClientRect())
```

Then, in `handleMouseDown` I log the coordinates that it receives.

```ts
export function handleMouseDown(event : MouseEvent) {
    drawing = true;

    const {clientX, clientY} = event;
    console.log(`mouseDown: x=${clientX}, y=${clientY}`)
    // [...]
}
```

And then I proceed to click as far top-left as I can manage.

![image](https://github.com/tobias0409/obsidian-cannote/assets/25849034/bbd0462b-12c3-47ba-8947-9fa732e4a21d)

This proves what I figured is happening: the `x` and `y` coordinates from the `event` in the mouse handler are sent "absolute" so to say, whereas in your code you would like them to be relative to the canvas.

In particular, the `top` and `left` keys from the DOMRect object are (perhaps with an off-by-1 error) the numbers you should add/subtract from `x` and `y` to get the relative values.

**Comment by tobias0409** [comment]
Thanks for pointing out the issue and pushed the fixed version.
